### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by jHoyne** [Tairraos/Poker.JS#3]
Are there any restrictions to using this? I would like to use it on a project I'm working on.

**Comment by Tairraos** [comment]
please go ahead, no restriction for all project, just don't remove my
copyright info.
enjoy.

2015-08-22 2:10 GMT+08:00 Joseph Hoyne <notifications@github.com>:

> Are there any restrictions to using this? I would like to use it on a
> project I'm working on.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Tairraos/Poker.JS/issues/3>.
>



-- 
致 诚挚的问候.

您的朋友 小乐
回复至: xiaole.tao@gmail.com

**Comment by jHoyne** [comment]
Thanks


On 22 August 2015 at 01:32, Tairraos <notifications@github.com> wrote:

> please go ahead, no restriction for all project, just don't remove my
> copyright info.
> enjoy.
>
> 2015-08-22 2:10 GMT+08:00 Joseph Hoyne <notifications@github.com>:
>
> > Are there any restrictions to using this? I would like to use it on a
> > project I'm working on.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Tairraos/Poker.JS/issues/3>.
> >
>
>
>
> --
> 致 诚挚的问候.
>
> 您的朋友 小乐
> 回复至: xiaole.tao@gmail.com
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Tairraos/Poker.JS/issues/3#issuecomment-133644616>.
>



-- 
Joseph Hoyne
Twitter <https://www.twitter.com/JosephHoyne>
Github <http://www.github.com/jHoyne>
