### ISSUE TITLE
移植到小程序效果有点差

### ISSUE THREAD

**Issue by JakeWoki** [Tairraos/Poker.JS#8]
![微信截图_20220302162635](https://user-images.githubusercontent.com/6948411/156324256-9de00526-96b8-45ab-a06c-a56dcbad8b4b.png)
小程序40的显示效果，锯齿好明显
![微信截图_20220302162811](https://user-images.githubusercontent.com/6948411/156324451-66986968-0486-49f6-bc3a-a7f00d50f1ce.png)
在小程序里打开webview120的效果，正常
这样要怎么优化呢？重新做大（还是小）的svg效果图更换原来的吗？

**Comment by JakeWoki** [comment]
参考https://blog.csdn.net/weixin_41547118/article/details/84595483

**Comment by Tairraos** [comment]
手机屏幕分辨率高，canvas需要2x绘制，就像普通素材图一样。画大的图缩小显示。



---原始邮件---
发件人: "Jake ***@***.***&gt;
发送时间: 2022年3月2日(周三) 下午4:33
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Tairraos/Poker.JS] 移植到小程序效果有点差 (Issue #8)




 

 小程序40的显示效果，锯齿好明显
 
 在小程序里打开webview120的效果，正常
 这样要怎么优化呢？重新做大（还是小）的svg效果图更换原来的吗？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
